// Seed populates the database with deterministic demo data.
//
// Properties of this seed:
//   - Reads DATABASE_URL through the same config loader the services use; no hardcoded fallback.
//   - Idempotent: every record has a deterministic UUID and uses ON CONFLICT (id) DO UPDATE,
//     so re-running updates fields without creating duplicates and without losing user-generated
//     data created on top of the seed.
//   - Transactional: nothing is committed unless the whole seed succeeds.
//   - Engagement (likes, comments, saves, notifications) is generated by joining real tables —
//     no hardcoded references to randomly-generated post UUIDs.
//
// Run:  go run ./cmd/seed
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/seeu/backend/config"
	"github.com/seeu/backend/pkg/probe"
)

// Deterministic UUID prefixes per entity. Suffix is the index, zero-padded to 12 chars.
const (
	pUser    = "a0000000-0000-0000-0000-"
	pBrand   = "b0000000-0000-0000-0000-"
	pPost    = "c0000000-0000-0000-0000-"
	pStory   = "d0000000-0000-0000-0000-"
	pHL      = "e0000000-0000-0000-0000-"
	pAudio   = "f0000000-0000-0000-0000-"
	pVidCat  = "10000000-0000-0000-0000-"
	pVideo   = "20000000-0000-0000-0000-"
	pReel    = "30000000-0000-0000-0000-"
	pFileCat = "40000000-0000-0000-0000-"
	pFile    = "50000000-0000-0000-0000-"
	pConv    = "60000000-0000-0000-0000-"
	pMsg     = "70000000-0000-0000-0000-"
	pComment = "80000000-0000-0000-0000-"
	pNotif   = "90000000-0000-0000-0000-"
	pSbor    = "aa000000-0000-0000-0000-"
)

func uid(prefix string, n int) string {
	return fmt.Sprintf("%s%012d", prefix, n)
}

type seedUser struct {
	id       string
	username string
	phone    string
	fullName string
	bio      string
	avatar   string
	gender   string
	verified bool
	devicePub string
}

var mainUsers = []seedUser{
	{uid(pUser, 1), "aidana_kz", "+77003309616", "Айдана Каримова", "Фотограф и путешественница. Алматы → весь мир.", "/uploads/seed/avatars/u1_aidana_kz.png", "female", true, "DEVICE_A001"},
	{uid(pUser, 2), "arman_dev", "+77001112233", "Арман Тулегенов", "Full-stack разработчик. Без кофе никуда.", "/uploads/seed/avatars/u2_arman_dev.png", "male", false, "DEVICE_A002"},
	{uid(pUser, 3), "dana_adventures", "+77002223344", "Дана Оспанова", "Горы, книги, закаты. Иногда море.", "/uploads/seed/avatars/u3_dana_adventures.png", "female", false, "DEVICE_A003"},
	{uid(pUser, 4), "timur_photo", "+77003334455", "Тимур Бекмуратов", "Стрит-фотография Алматы. Каждый день — кадр.", "/uploads/seed/avatars/u4_timur_photo.png", "male", true, "DEVICE_A004"},
	{uid(pUser, 5), "aisha_fit", "+77004445566", "Айша Нурланкызы", "Фитнес-тренер. Здоровое тело — здоровая жизнь.", "/uploads/seed/avatars/u5_aisha_fit.png", "female", false, "DEVICE_A005"},
	{uid(pUser, 6), "nursultan_eats", "+77005556677", "Нурсултан Кажимов", "Фуд-блогер. Лучшие места Астаны и Алматы.", "/uploads/seed/avatars/u6_nursultan_eats.png", "male", false, "DEVICE_A006"},
	{uid(pUser, 7), "zarina_art", "+77006667788", "Зарина Муханова", "Диджитал-художник и иллюстратор. Заказы открыты.", "/uploads/seed/avatars/u7_zarina_art.png", "female", false, "DEVICE_A007"},
	{uid(pUser, 8), "bekzat_travel", "+77007778899", "Бекзат Асанов", "Путешествую по Центральной Азии. Делюсь маршрутами.", "/uploads/seed/avatars/u8_bekzat_travel.png", "male", false, "DEVICE_A008"},
	{uid(pUser, 9), "madina_style", "+77008889900", "Мадина Айткали", "Стиль и дизайн. Минимализм с характером.", "/uploads/seed/avatars/u9_madina_style.png", "female", false, "DEVICE_A009"},
	{uid(pUser, 10), "kairat_music", "+77009990011", "Кайрат Бектуров", "Продюсер и диджей. Электроника, синтвейв.", "/uploads/seed/avatars/u10_kairat_music.png", "male", true, "DEVICE_A010"},
}

var brandUsers = []seedUser{
	{uid(pBrand, 1), "almaty_vibes", "+77010000001", "Алматы Vibes", "Городская жизнь Алматы — каждый день.", "/uploads/seed/avatars/b1_almaty_vibes.png", "other", true, ""},
	{uid(pBrand, 2), "kazakh_chef", "+77010000002", "Казахская кухня", "Рецепты и культура национальной еды.", "/uploads/seed/avatars/b2_kazakh_chef.png", "other", true, ""},
	{uid(pBrand, 3), "astana_nights", "+77010000003", "Астана Nights", "Ночная жизнь и события столицы.", "/uploads/seed/avatars/b3_astana_nights.png", "other", false, ""},
	{uid(pBrand, 4), "tech_nomad_kz", "+77010000004", "Tech Nomad KZ", "Технологии и жизнь цифровых кочевников.", "/uploads/seed/avatars/b4_tech_nomad_kz.png", "other", false, ""},
	{uid(pBrand, 5), "dance_almaty", "+77010000005", "Танцы Алматы", "Танцевальные студии и события города.", "/uploads/seed/avatars/b5_dance_almaty.png", "other", false, ""},
}

func allUsers() []seedUser { return append(append([]seedUser{}, mainUsers...), brandUsers...) }

type seedPost struct {
	idx        int    // global post index, 1-based
	ownerIdx   int    // 1-based index into mainUsers
	caption    string
	mediaURLs  []string
	mediaTypes []string
	location   string
}

// 30 posts total — 3 per main user. Captions, locations — на русском.
var posts = []seedPost{
	{1, 1, "Закат над горами Алматы — весь день ждала этот кадр", arr("/uploads/seed/photos/p1a.jpg", "/uploads/seed/photos/p1b.jpg"), arr("image", "image"), "Алматы"},
	{2, 1, "Утренние ритуалы — кофе и тихие минуты", arr("/uploads/seed/photos/p2.jpg"), arr("image"), "Дом"},
	{3, 1, "Тестирую новую камеру. Кажется, влюбилась", arr("/uploads/seed/photos/p3a.jpg", "/uploads/seed/photos/p3b.jpg", "/uploads/seed/photos/p3c.jpg"), arr("image", "image", "image"), "Кок-Тобе"},
	{4, 2, "Рабочее место 2026 — наконец-то оранжевый акцент", arr("/uploads/seed/photos/p4a.jpg", "/uploads/seed/photos/p4b.jpg"), arr("image", "image"), "Домашний офис"},
	{5, 2, "Команда взяла первое место на хакатоне!", arr("/uploads/seed/photos/p5.jpg"), arr("image"), "Astana Hub"},
	{6, 2, "Новая механическая клавиатура — звук как у эспрессо-машины", arr("/uploads/seed/photos/p6.jpg"), arr("image"), ""},
	{7, 3, "Чарын — невероятное место. Каньон будто с другой планеты", arr("/uploads/seed/photos/p7a.jpg", "/uploads/seed/photos/p7b.jpg"), arr("image", "image"), "Каньон Чарын"},
	{8, 3, "Книжный совет недели — «Sapiens» Юваля Харари", arr("/uploads/seed/photos/p8.jpg"), arr("image"), ""},
	{9, 3, "Первый снег в этом сезоне. Шымбулак ждёт", arr("/uploads/seed/photos/p9.jpg"), arr("image"), "Шымбулак"},
	{10, 4, "Золотой час в городе — лучшие 20 минут дня", arr("/uploads/seed/photos/p10a.jpg", "/uploads/seed/photos/p10b.jpg"), arr("image", "image"), "Алматы"},
	{11, 4, "Портретная съёмка в парке. Свет был идеальный", arr("/uploads/seed/photos/p11a.jpg", "/uploads/seed/photos/p11b.jpg"), arr("image", "image"), "Центральный парк"},
	{12, 4, "За кадром нашей студийной съёмки", arr("/uploads/seed/photos/p12.jpg"), arr("image"), "Студия"},
	{13, 5, "Утренняя тренировка — пятница в режиме бога", arr("/uploads/seed/photos/p13.jpg"), arr("image"), "Зал"},
	{14, 5, "Полезный мил-преп на неделю. Делюсь рецептами", arr("/uploads/seed/photos/p14.jpg"), arr("image"), "Кухня"},
	{15, 5, "Прогресс подготовки к марафону — три месяца до старта", arr("/uploads/seed/photos/p15.jpg"), arr("image"), "Алматы Марафон"},
	{16, 6, "Лучший плов города — нашёл место для своих", arr("/uploads/seed/photos/p16.jpg"), arr("image"), "Алматы"},
	{17, 6, "Обзор нового ресторана в Астане. Кухня — космос", arr("/uploads/seed/photos/p17a.jpg", "/uploads/seed/photos/p17b.jpg"), arr("image", "image"), "Астана"},
	{18, 6, "Домашний бешбармак по бабушкиному рецепту", arr("/uploads/seed/photos/p18.jpg"), arr("image"), "Дом"},
	{19, 7, "Новая иллюстрация готова — серия «Город»", arr("/uploads/seed/photos/p19.jpg"), arr("image"), "Студия"},
	{20, 7, "Процесс работы над иллюстрацией — слой за слоем", arr("/uploads/seed/photos/p20.jpg"), arr("image"), ""},
	{21, 7, "Коммерческий заказ — обложка для альбома", arr("/uploads/seed/photos/p21.jpg"), arr("image"), ""},
	{22, 8, "Старый Ташкент — узкие улочки и аромат лепёшек", arr("/uploads/seed/photos/p22.jpg"), arr("image"), "Ташкент"},
	{23, 8, "Бишкек, утро. Айран и горы на горизонте", arr("/uploads/seed/photos/p23.jpg"), arr("image"), "Бишкек"},
	{24, 8, "Заметки о пересечении границ — что взять с собой", arr("/uploads/seed/photos/p24.jpg"), arr("image"), ""},
	{25, 9, "Весенний лукбук — пастель и оверсайз", arr("/uploads/seed/photos/p25a.jpg", "/uploads/seed/photos/p25b.jpg"), arr("image", "image"), "Алматы"},
	{26, 9, "Подборка локальных дизайнеров. Поддержим своих", arr("/uploads/seed/photos/p26.jpg"), arr("image"), ""},
	{27, 9, "Винтажные находки на барахолке. Кожа, шерсть, история", arr("/uploads/seed/photos/p27.jpg"), arr("image"), ""},
	{28, 10, "Студийная сессия — пишем новый трек", arr("/uploads/seed/photos/p28.jpg"), arr("image"), "Студия"},
	{29, 10, "Сегодня лайв-сет в клубе. Adres в сторис", arr("/uploads/seed/photos/p29.jpg"), arr("image"), "Алматы"},
	{30, 10, "Новый трек скоро на всех площадках", arr("/uploads/seed/photos/p30.jpg"), arr("image"), ""},

	// Расширение до 50 постов — ещё по 2 на каждого main user'а.
	{31, 1, "Тёплый кадр перед рассветом — стоит того", arr("/uploads/seed/photos/p31.jpg"), arr("image"), "Алматы"},
	{32, 1, "Чёрно-белая серия из старого центра", arr("/uploads/seed/photos/p32.jpg"), arr("image"), "Панфилова"},
	{33, 2, "Новый PR смержен — деплой пошёл", arr("/uploads/seed/photos/p33a.jpg", "/uploads/seed/photos/p33b.jpg"), arr("image", "image"), "Astana Hub"},
	{34, 2, "Сетап на конференцию готов — встречу всех на стенде", arr("/uploads/seed/photos/p34.jpg"), arr("image"), "EXPO"},
	{35, 3, "Книжная полка пополнилась — ноябрьский улов", arr("/uploads/seed/photos/p35.jpg"), arr("image"), ""},
	{36, 3, "Прогулка по Кок-Жайляу — снег почти растаял", arr("/uploads/seed/photos/p36a.jpg", "/uploads/seed/photos/p36b.jpg"), arr("image", "image"), "Кок-Жайляу"},
	{37, 4, "Один день из жизни уличного фотографа", arr("/uploads/seed/photos/p37.jpg"), arr("image"), "Алматы"},
	{38, 4, "Кадр-победитель в этом месяце — спасибо за голоса", arr("/uploads/seed/photos/p38.jpg"), arr("image"), ""},
	{39, 5, "Силовая тренировка — присед, становая, жим. Прогресс есть", arr("/uploads/seed/photos/p39.jpg"), arr("image"), "Зал"},
	{40, 5, "Послетренировочный смузи — рецепт в сторис", arr("/uploads/seed/photos/p40.jpg"), arr("image"), ""},
	{41, 6, "Завтрак в новом кафе на Желтоксана — рекомендую", arr("/uploads/seed/photos/p41.jpg"), arr("image"), "Алматы"},
	{42, 6, "Самса от тёти Гульнары — лучшая в городе", arr("/uploads/seed/photos/p42a.jpg", "/uploads/seed/photos/p42b.jpg"), arr("image", "image"), "Зелёный базар"},
	{43, 7, "Скетч персонажа для нового проекта", arr("/uploads/seed/photos/p43.jpg"), arr("image"), ""},
	{44, 7, "Готовлюсь к выставке — финальная серия работ", arr("/uploads/seed/photos/p44.jpg"), arr("image"), "Алматы"},
	{45, 8, "Самарканд — голубые купола и тишина утра", arr("/uploads/seed/photos/p45.jpg"), arr("image"), "Самарканд"},
	{46, 8, "Душанбе — Памирские горы на фоне", arr("/uploads/seed/photos/p46.jpg"), arr("image"), "Душанбе"},
	{47, 9, "Осенний лукбук — твид и шерсть", arr("/uploads/seed/photos/p47a.jpg", "/uploads/seed/photos/p47b.jpg"), arr("image", "image"), "Алматы"},
	{48, 9, "Капсульный гардероб — 12 вещей на сезон", arr("/uploads/seed/photos/p48.jpg"), arr("image"), ""},
	{49, 10, "Микшируем альбом — финальные правки", arr("/uploads/seed/photos/p49.jpg"), arr("image"), "Студия"},
	{50, 10, "Афиша готова — следующий лайв через 2 недели", arr("/uploads/seed/photos/p50.jpg"), arr("image"), "Алматы"},
}

func arr(s ...string) []string { return s }

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	ctx := context.Background()
	pool, err := pgxpool.New(ctx, cfg.Database.URL)
	if err != nil {
		log.Fatalf("connect db: %v", err)
	}
	defer pool.Close()

	if err := pool.Ping(ctx); err != nil {
		log.Fatalf("ping db: %v", err)
	}

	tx, err := pool.Begin(ctx)
	if err != nil {
		log.Fatalf("begin tx: %v", err)
	}
	committed := false
	defer func() {
		if !committed {
			_ = tx.Rollback(ctx)
		}
	}()

	steps := []struct {
		name string
		fn   func(context.Context, pgx.Tx) error
	}{
		{"clean_demo", cleanDemoData},
		{"users", seedAllUsers},
		{"audio_tracks", seedAudioTracks},
		{"video_categories", seedVideoCategories},
		{"file_categories", seedFileCategories},
		{"posts", seedPosts},
		// video_posts MUST run before likes_on_posts / saved_posts —
		// the JOIN-based engagement steps iterate all rows in `posts`,
		// so any post inserted later misses engagement on first run and
		// catches up on second run, breaking idempotency.
		{"video_posts", seedVideoPosts},
		{"stories", seedStories},
		{"highlights", seedHighlights},
		{"comments", seedComments},
		{"likes_on_posts", seedLikesOnPosts},
		{"saved_posts", seedSavedPosts},
		{"follows", seedFollows},
		{"notifications", seedNotifications},
		{"conversations", seedConversations},
		{"videos", seedVideos},
		{"files", seedFiles},
		{"sbory", seedSbory},
		{"counters", recountCounters},
	}

	for _, s := range steps {
		if err := s.fn(ctx, tx); err != nil {
			log.Fatalf("seed step %q failed: %v", s.name, err)
		}
		fmt.Printf("  %-20s ok\n", s.name)
	}

	if err := tx.Commit(ctx); err != nil {
		log.Fatalf("commit: %v", err)
	}
	committed = true

	fmt.Println()
	fmt.Println("seed complete.")
	fmt.Println("login: any phone from above + OTP 0000")
}

// ---------- Cleanup ----------

// cleanDemoData wipes tables we fully own (catalogues + their dependents) so
// re-seeds are deterministic. Anything user-generated outside these tables
// (posts, comments, likes, follows, chats, stories) is preserved across runs.
func cleanDemoData(ctx context.Context, tx pgx.Tx) error {
	stmts := []string{
		// Удаляем group-чаты, привязанные к seed-сборам (созданы в процессе тестирования).
		// conversation_participants и messages удаляются каскадно (ON DELETE CASCADE).
		`DELETE FROM conversations WHERE id IN (SELECT chat_id FROM sbory WHERE id::text LIKE 'aa000000%' AND chat_id IS NOT NULL)`,
		`DELETE FROM sbor_members WHERE sbor_id IN (SELECT id FROM sbory WHERE id::text LIKE 'aa000000%')`,
		`DELETE FROM sbory WHERE id::text LIKE 'aa000000%'`,
		`DELETE FROM video_views`,
		`DELETE FROM video_likes`,
		`DELETE FROM videos`,
		`DELETE FROM video_categories`,
		`DELETE FROM file_downloads`,
		`DELETE FROM files`,
		`DELETE FROM file_categories`,
		`DELETE FROM audio_tracks`,
	}
	for _, q := range stmts {
		if _, err := tx.Exec(ctx, q); err != nil {
			return fmt.Errorf("clean (%s): %w", q, err)
		}
	}
	return nil
}

// ---------- Users ----------

func seedAllUsers(ctx context.Context, tx pgx.Tx) error {
	for _, u := range allUsers() {
		_, err := tx.Exec(ctx, `
			INSERT INTO users (id, username, phone, full_name, bio, avatar_url, gender, is_verified, device_public_id)
			VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
			ON CONFLICT (id) DO UPDATE SET
				username = EXCLUDED.username,
				phone = EXCLUDED.phone,
				full_name = EXCLUDED.full_name,
				bio = EXCLUDED.bio,
				avatar_url = EXCLUDED.avatar_url,
				gender = EXCLUDED.gender,
				is_verified = EXCLUDED.is_verified,
				device_public_id = EXCLUDED.device_public_id`,
			u.id, u.username, u.phone, u.fullName, u.bio, u.avatar, u.gender, u.verified, u.devicePub)
		if err != nil {
			return fmt.Errorf("upsert user %s: %w", u.username, err)
		}
	}
	// Promote the first main user to admin so the admin web has a working login
	// against a freshly seeded database.
	if _, err := tx.Exec(ctx, `UPDATE users SET is_admin = true WHERE id = $1`, uid(pUser, 1)); err != nil {
		return fmt.Errorf("promote first user to admin: %w", err)
	}
	return nil
}

// ---------- Catalogues ----------

func seedAudioTracks(ctx context.Context, tx pgx.Tx) error {
	// Реальные классические треки из общественного достояния (Wikimedia Commons).
	// Имя композитора и название произведения совпадают с реальным контентом файла —
	// больше никаких «Летний гимн от DJ Алматы» с длиной 4 секунды (sound effect).
	// Длительность пробивается ffprobe'ом из самого файла.
	tracks := []struct {
		idx    int
		title  string
		artist string
		genre  string
		file   string // относительно backend/
	}{
		{1, "Eine kleine Nachtmusik — 1. Allegro", "Вольфганг Амадей Моцарт", "классика", "uploads/seed/audio/mozart_eine_kleine_allegro.ogg"},
		{2, "Симфония №40 соль минор — 1. Molto allegro", "Вольфганг Амадей Моцарт", "классика", "uploads/seed/audio/mozart_symphony_40_allegro.ogg"},
		{3, "Бранденбургский концерт №1 — 1. Allegro", "Иоганн Себастьян Бах", "барокко", "uploads/seed/audio/bach_brandenburg_1_allegro.ogg"},
		{4, "Симфония №5 до минор — 1. Allegro con brio", "Людвиг ван Бетховен", "классика", "uploads/seed/audio/beethoven_symphony_5_allegro.ogg"},
		{5, "Ноктюрн соч. 32 №1", "Фредерик Шопен", "романтизм", "uploads/seed/audio/chopin_nocturne_op32_1.ogg"},
		{6, "«Времена года» — Весна, 1. Allegro", "Антонио Вивальди", "барокко", "uploads/seed/audio/vivaldi_spring_allegro.oga"},
		{7, "Лунный свет (Clair de Lune)", "Клод Дебюсси", "импрессионизм", "uploads/seed/audio/debussy_clair_de_lune.ogg"},
		{8, "Лебединое озеро — Сцена (Moderato)", "Пётр Ильич Чайковский", "романтизм", "uploads/seed/audio/tchaikovsky_swan_lake.ogg"},
		{9, "Утреннее настроение (Пер Гюнт)", "Эдвард Григ", "романтизм", "uploads/seed/audio/grieg_morning_mood.ogg"},
		{10, "Гимнопедия №1", "Эрик Сати", "импрессионизм", "uploads/seed/audio/satie_gymnopedie_1.ogg"},
	}
	for _, t := range tracks {
		duration := probe.DurationSeconds(t.file)
		if duration == 0 {
			return fmt.Errorf("audio probe failed for %s — file missing or ffprobe not on PATH (run scripts/seed_assets/download.ps1 first)", t.file)
		}
		_, err := tx.Exec(ctx, `
			INSERT INTO audio_tracks (id, title, artist, cover_url, audio_url, duration_seconds, genre)
			VALUES ($1,$2,$3,$4,$5,$6,$7)
			ON CONFLICT (id) DO UPDATE SET
				title = EXCLUDED.title,
				artist = EXCLUDED.artist,
				cover_url = EXCLUDED.cover_url,
				audio_url = EXCLUDED.audio_url,
				duration_seconds = EXCLUDED.duration_seconds,
				genre = EXCLUDED.genre`,
			uid(pAudio, t.idx), t.title, t.artist,
			fmt.Sprintf("/uploads/seed/covers/a%d.jpg", t.idx),
			"/"+t.file,
			duration, t.genre)
		if err != nil {
			return err
		}
	}
	return nil
}

func seedVideoCategories(ctx context.Context, tx pgx.Tx) error {
	cats := []string{"Влог", "Музыка", "Образование", "Спорт", "Юмор"}
	for i, name := range cats {
		_, err := tx.Exec(ctx, `
			INSERT INTO video_categories (id, name) VALUES ($1,$2)
			ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name`,
			uid(pVidCat, i+1), name)
		if err != nil {
			return err
		}
	}
	return nil
}

func seedFileCategories(ctx context.Context, tx pgx.Tx) error {
	cats := []string{"Документы", "Аудио", "Видео", "Изображения", "Прочее"}
	for i, name := range cats {
		_, err := tx.Exec(ctx, `
			INSERT INTO file_categories (id, name) VALUES ($1,$2)
			ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name`,
			uid(pFileCat, i+1), name)
		if err != nil {
			return err
		}
	}
	return nil
}

// ---------- Posts ----------

func seedPosts(ctx context.Context, tx pgx.Tx) error {
	for _, p := range posts {
		ownerID := uid(pUser, p.ownerIdx)
		postID := uid(pPost, p.idx)
		_, err := tx.Exec(ctx, `
			INSERT INTO posts (id, user_id, caption, media_urls, media_types, location, thumbnail_url)
			VALUES ($1,$2,$3,$4,$5,$6,'')
			ON CONFLICT (id) DO UPDATE SET
				caption = EXCLUDED.caption,
				media_urls = EXCLUDED.media_urls,
				media_types = EXCLUDED.media_types,
				location = EXCLUDED.location`,
			postID, ownerID, p.caption, p.mediaURLs, p.mediaTypes, p.location)
		if err != nil {
			return fmt.Errorf("upsert post %d: %w", p.idx, err)
		}
	}
	return nil
}

// ---------- Stories ----------

func seedStories(ctx context.Context, tx pgx.Tx) error {
	// One active story per main user.
	for i := 1; i <= len(mainUsers); i++ {
		_, err := tx.Exec(ctx, `
			INSERT INTO stories (id, user_id, media_url, media_type, text_overlay, expires_at)
			VALUES ($1,$2,$3,'image',$4, NOW() + INTERVAL '20 hours')
			ON CONFLICT (id) DO UPDATE SET
				media_url = EXCLUDED.media_url,
				text_overlay = EXCLUDED.text_overlay,
				expires_at = EXCLUDED.expires_at`,
			uid(pStory, i), uid(pUser, i),
			fmt.Sprintf("/uploads/seed/stories/s%d.jpg", i),
			fmt.Sprintf("Сторис %d", i))
		if err != nil {
			return err
		}
	}
	// One expired story per first 5 users — pinned to highlights below.
	for i := 1; i <= 5; i++ {
		_, err := tx.Exec(ctx, `
			INSERT INTO stories (id, user_id, media_url, media_type, text_overlay, expires_at)
			VALUES ($1,$2,$3,'image','', NOW() - INTERVAL '48 hours')
			ON CONFLICT (id) DO UPDATE SET
				media_url = EXCLUDED.media_url,
				expires_at = EXCLUDED.expires_at`,
			uid(pStory, 100+i), uid(pUser, i),
			fmt.Sprintf("/uploads/seed/stories/hl%d.jpg", i))
		if err != nil {
			return err
		}
	}
	return nil
}

func seedHighlights(ctx context.Context, tx pgx.Tx) error {
	for i := 1; i <= 5; i++ {
		hlID := uid(pHL, i)
		_, err := tx.Exec(ctx, `
			INSERT INTO highlights (id, user_id, title, cover_url)
			VALUES ($1,$2,$3,$4)
			ON CONFLICT (id) DO UPDATE SET
				title = EXCLUDED.title,
				cover_url = EXCLUDED.cover_url`,
			hlID, uid(pUser, i),
			[]string{"Поездки", "Студия", "Природа", "Друзья", "Любимое"}[(i-1)%5],
			fmt.Sprintf("/uploads/seed/highlights/h%d.jpg", i))
		if err != nil {
			return err
		}
		_, err = tx.Exec(ctx, `
			INSERT INTO highlight_stories (highlight_id, story_id)
			VALUES ($1,$2)
			ON CONFLICT DO NOTHING`,
			hlID, uid(pStory, 100+i))
		if err != nil {
			return err
		}
	}
	return nil
}

// ---------- Engagement ----------

var commentTemplates = []string{
	"Огонь!", "Цвета невероятные", "Вау, вид супер", "А где это снято?",
	"Кайф", "Поздравляю!", "Топчик", "Отличная работа!", "Шикарно",
	"Свет идеальный", "Очень вдохновляет", "Цели!", "Так держать!",
	"Невероятно", "Талантище", "Стиль безупречен",
}

func seedComments(ctx context.Context, tx pgx.Tx) error {
	cnt := 0
	for _, p := range posts {
		// Each post gets 2-3 comments from users that aren't the owner. Deterministic.
		for k := 1; k <= 3; k++ {
			commenterIdx := ((p.idx*7 + k*11) % len(mainUsers)) + 1
			if commenterIdx == p.ownerIdx {
				commenterIdx = (commenterIdx % len(mainUsers)) + 1
			}
			tmpl := commentTemplates[(p.idx+k)%len(commentTemplates)]
			cnt++
			_, err := tx.Exec(ctx, `
				INSERT INTO comments (id, post_id, user_id, text)
				VALUES ($1,$2,$3,$4)
				ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text`,
				uid(pComment, cnt), uid(pPost, p.idx), uid(pUser, commenterIdx), tmpl)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func seedLikesOnPosts(ctx context.Context, tx pgx.Tx) error {
	// Engagement is generated by JOIN — no hardcoded post UUIDs anywhere.
	// Rule: every user (main + brand) likes ~70% of posts, except their own.
	_, err := tx.Exec(ctx, `
		INSERT INTO likes (user_id, entity_id, entity_type)
		SELECT u.id, p.id, 'post'
		FROM users u
		CROSS JOIN posts p
		WHERE u.id != p.user_id
		  AND (hashtext(u.id::text || p.id::text) % 10) < 7
		ON CONFLICT (user_id, entity_id, entity_type) DO NOTHING`)
	return err
}

func seedSavedPosts(ctx context.Context, tx pgx.Tx) error {
	_, err := tx.Exec(ctx, `
		INSERT INTO saved_posts (user_id, post_id)
		SELECT u.id, p.id
		FROM users u
		CROSS JOIN posts p
		WHERE u.id != p.user_id
		  AND (hashtext(u.id::text || p.id::text) % 10) < 2
		ON CONFLICT DO NOTHING`)
	return err
}

func seedFollows(ctx context.Context, tx pgx.Tx) error {
	// Every main user follows every other main user.
	if _, err := tx.Exec(ctx, `
		INSERT INTO follows (follower_id, following_id)
		SELECT a.id, b.id
		FROM users a
		CROSS JOIN users b
		WHERE a.id != b.id
		  AND a.id::text LIKE 'a0000000%'
		  AND b.id::text LIKE 'a0000000%'
		ON CONFLICT DO NOTHING`); err != nil {
		return err
	}
	// Every main user follows every brand.
	_, err := tx.Exec(ctx, `
		INSERT INTO follows (follower_id, following_id)
		SELECT a.id, b.id
		FROM users a
		CROSS JOIN users b
		WHERE a.id::text LIKE 'a0000000%'
		  AND b.id::text LIKE 'b0000000%'
		ON CONFLICT DO NOTHING`)
	return err
}

func seedNotifications(ctx context.Context, tx pgx.Tx) error {
	// Wipe & rebuild: notifications are derived state, easier to regenerate from current relations.
	if _, err := tx.Exec(ctx, `
		DELETE FROM notifications WHERE id::text LIKE '90000000%'`); err != nil {
		return err
	}
	// One notif per like, one per comment, one per follow — capped to keep the table sane.
	queries := []string{
		`INSERT INTO notifications (id, user_id, from_user_id, type, entity_id, entity_type, message)
		 SELECT ('` + pNotif + `' || lpad((row_number() OVER ())::text, 12, '0'))::uuid,
		        p.user_id, l.user_id, 'like', p.id, 'post', 'liked your post'
		 FROM likes l JOIN posts p ON p.id = l.entity_id
		 WHERE l.entity_type = 'post' AND p.user_id != l.user_id
		 LIMIT 30
		 ON CONFLICT (id) DO NOTHING`,
		`INSERT INTO notifications (id, user_id, from_user_id, type, entity_id, entity_type, message)
		 SELECT ('` + pNotif + `1' || lpad((row_number() OVER ())::text, 11, '0'))::uuid,
		        p.user_id, c.user_id, 'comment', p.id, 'post', 'commented on your post'
		 FROM comments c JOIN posts p ON p.id = c.post_id
		 WHERE p.user_id != c.user_id
		 LIMIT 30
		 ON CONFLICT (id) DO NOTHING`,
		`INSERT INTO notifications (id, user_id, from_user_id, type, message)
		 SELECT ('` + pNotif + `2' || lpad((row_number() OVER ())::text, 11, '0'))::uuid,
		        f.following_id, f.follower_id, 'follow', 'started following you'
		 FROM follows f
		 LIMIT 30
		 ON CONFLICT (id) DO NOTHING`,
	}
	for _, q := range queries {
		if _, err := tx.Exec(ctx, q); err != nil {
			return err
		}
	}
	return nil
}

// ---------- Chats ----------

func seedConversations(ctx context.Context, tx pgx.Tx) error {
	convs := []struct {
		idx          int
		participants [2]int
		messages     []struct {
			senderIdx int
			text      string
		}
	}{
		{1, [2]int{1, 2}, []struct {
			senderIdx int
			text      string
		}{
			{1, "Привет! Видела твой последний пост, огонь"},
			{2, "Спасибо! Только что задеплоил"},
			{1, "Поделишься потом стеком?"},
			{2, "Конечно, в личку напишу"},
		}},
		{2, [2]int{1, 4}, []struct {
			senderIdx int
			text      string
		}{
			{1, "Когда следующий шут?"},
			{4, "В субботу, в студии"},
			{1, "Кинь точку"},
		}},
		{3, [2]int{1, 3}, []struct {
			senderIdx int
			text      string
		}{
			{3, "В Чарын едем?"},
			{1, "Когда планируешь?"},
			{3, "В пятницу с утра"},
			{1, "Я в деле"},
			{3, "Договорились"},
		}},
	}
	for _, c := range convs {
		convID := uid(pConv, c.idx)
		if _, err := tx.Exec(ctx, `
			INSERT INTO conversations (id) VALUES ($1)
			ON CONFLICT (id) DO NOTHING`, convID); err != nil {
			return err
		}
		for _, p := range c.participants {
			if _, err := tx.Exec(ctx, `
				INSERT INTO conversation_participants (conversation_id, user_id)
				VALUES ($1,$2) ON CONFLICT DO NOTHING`,
				convID, uid(pUser, p)); err != nil {
				return err
			}
		}
		for j, m := range c.messages {
			msgIdx := c.idx*100 + j + 1
			if _, err := tx.Exec(ctx, `
				INSERT INTO messages (id, conversation_id, sender_id, text)
				VALUES ($1,$2,$3,$4)
				ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text`,
				uid(pMsg, msgIdx), convID, uid(pUser, m.senderIdx), m.text); err != nil {
				return err
			}
		}
	}
	return nil
}

// ---------- Videos / Reels ----------

func seedVideos(ctx context.Context, tx pgx.Tx) error {
	// Real local mp4 files в backend/uploads/videos/. Cycle through them so we
	// have 6 entries even though there are only 3 source files — content
	// duplication is fine for seed purposes. Длительность пробивается ffprobe'ом.
	// Седьмая запись — реальный полнометражный public-domain фильм Чарли Чаплина
	// (≈25 минут), хранится в uploads/seed/movies/.
	clips := []string{"forest", "synth_build", "tokyo_3am"}
	videos := []struct {
		idx       int
		owner     int
		category  int
		title     string
		desc      string
		videoPath string // empty → use clips[idx-1]; non-empty → custom path
		thumbPath string // same convention
	}{
		{1, 1, 1, "Алматы — травел-влог за один день", "", "", ""},
		{2, 4, 1, "Фото-прогулка зимой по центру города", "", "", ""},
		{3, 5, 4, "Подготовка к марафону — день 30", "", "", ""},
		{4, 6, 1, "Мастер-класс: настоящий узбекский плов", "", "", ""},
		{5, 7, 2, "Процесс работы над иллюстрацией", "", "", ""},
		{6, 10, 2, "Лайв-сет от DJ Кайрата — премьера", "", "", ""},
		{8, 3, 3, "Прогулка по городу — утренний обзор", "Утренняя прогулка по центру города. Атмосфера и ритм улиц.", "uploads/videos/city_walk.mp4", "uploads/videos/city_walk_thumb.jpg"},
		{9, 8, 1, "Природа и утренний свет", "Рассвет в горах — спокойствие и красота природы.", "uploads/videos/nature_morning.mp4", "uploads/videos/nature_morning_thumb.jpg"},
		{10, 2, 3, "Ночная поездка по городу", "Огни ночного города из окна машины. Атмосферный таймлапс.", "uploads/videos/night_drive.mp4", "uploads/videos/night_drive_thumb.jpg"},
		{11, 10, 2, "Запись в студии — создание трека", "Процесс создания электронного трека от идеи до мастеринга.", "uploads/videos/music_studio.mp4", "uploads/videos/music_studio_thumb.jpg"},
		{12, 9, 1, "Модный показ Алматы 2026", "Обзор модного показа локальных дизайнеров в Алматы.", "uploads/videos/forest.mp4", "uploads/videos/forest_thumb.jpg"},
	}
	for _, v := range videos {
		var videoFile, thumbFile string
		if v.videoPath != "" {
			videoFile = v.videoPath
			thumbFile = v.thumbPath
		} else {
			f := clips[(v.idx-1)%len(clips)]
			videoFile = fmt.Sprintf("uploads/videos/%s.mp4", f)
			thumbFile = fmt.Sprintf("uploads/videos/%s_thumb.jpg", f)
		}
		duration := probe.DurationSeconds(videoFile)
		if duration == 0 {
			return fmt.Errorf("video probe failed for %s — file missing or ffprobe not on PATH", videoFile)
		}
		_, err := tx.Exec(ctx, `
			INSERT INTO videos (id, user_id, title, description, video_url, thumbnail_url, duration_seconds, category_id, resolution)
			VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'')
			ON CONFLICT (id) DO UPDATE SET
				title = EXCLUDED.title,
				description = EXCLUDED.description,
				video_url = EXCLUDED.video_url,
				thumbnail_url = EXCLUDED.thumbnail_url,
				duration_seconds = EXCLUDED.duration_seconds,
				category_id = EXCLUDED.category_id`,
			uid(pVideo, v.idx), uid(pUser, v.owner), v.title, v.desc,
			"/"+videoFile,
			"/"+thumbFile,
			duration, uid(pVidCat, v.category))
		if err != nil {
			return err
		}
	}
	return nil
}

// seedVideoPosts inserts video publications into the unified `posts` table
// (after migration 23, reels are gone — video content lives here). Mp4 files
// in backend/uploads/reels/ get reused as media_urls.
func seedVideoPosts(ctx context.Context, tx pgx.Tx) error {
	reelFiles := []string{"r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10"}
	rows := []struct {
		idx      int
		owner    int
		audio    int
		caption  string
		hashtags []string
	}{
		{1, 1, 1, "Утро в горах — солнце поднимается над хребтом", arr("алматы", "утро", "горы")},
		{2, 4, 3, "Улицы ночью — фонари и мокрый асфальт", arr("фото", "алматы", "ночь")},
		{3, 5, 4, "30 дней челлендж — день первый", arr("фитнес", "челлендж")},
		{4, 7, 5, "Процесс скетча — слой за слоем", arr("арт", "процесс")},
		{5, 9, 1, "Весенний лукбук — пастель и оверсайз", arr("стиль", "мода")},
		{6, 10, 3, "Превью лайв-микса — синтвейв ночь", arr("музыка", "диджей")},
		{7, 2, 7, "Код на закате — терминал и горы", arr("разработка", "код", "алматы")},
		{8, 3, 8, "Горная тропа — утренний поход", arr("поход", "природа", "горы")},
		{9, 6, 9, "Готовим на огне — бараньи рёбра", arr("еда", "готовка", "гриль")},
		{10, 8, 10, "Бишкек на рассвете — вид с крыши", arr("путешествие", "бишкек", "рассвет")},
		{11, 1, 2, "Ночной Алматы — огни и тишина", arr("алматы", "ночь", "город")},
		{12, 4, 6, "Кадры дня — стрит-фотография", arr("фото", "стрит", "город")},
	}
	for _, r := range rows {
		f := reelFiles[(r.idx-1)%len(reelFiles)]
		mediaURL := fmt.Sprintf("/uploads/reels/%s.mp4", f)
		thumbURL := fmt.Sprintf("/uploads/reels/thumbs/%s_thumb.jpg", f)
		caption := r.caption
		if len(r.hashtags) > 0 {
			tags := ""
			for i, h := range r.hashtags {
				if i > 0 {
					tags += " "
				}
				tags += "#" + h
			}
			caption = caption + "\n\n" + tags
		}
		_, err := tx.Exec(ctx, `
			INSERT INTO posts (id, user_id, caption, media_urls, media_types, location, audio_track_id, thumbnail_url)
			VALUES ($1, $2, $3, $4, ARRAY['video'], '', $5, $6)
			ON CONFLICT (id) DO UPDATE SET
				caption = EXCLUDED.caption,
				media_urls = EXCLUDED.media_urls,
				media_types = EXCLUDED.media_types,
				audio_track_id = EXCLUDED.audio_track_id,
				thumbnail_url = EXCLUDED.thumbnail_url`,
			uid(pReel, r.idx), uid(pUser, r.owner), caption,
			[]string{mediaURL}, uid(pAudio, r.audio), thumbURL)
		if err != nil {
			return err
		}
	}
	return nil
}

// ---------- Library ----------

func seedFiles(ctx context.Context, tx pgx.Tx) error {
	// All files point at real local blobs in backend/uploads/seed/library/.
	// Sizes are read from disk so the displayed size matches what the user
	// actually downloads — never hardcoded.
	files := []struct {
		idx      int
		owner    int
		category int
		name     string
		mime     string
		path     string // disk-relative; used to stat real size + serve via static handler
	}{
		{1, 2, 1, "План проекта.pdf", "application/pdf", "uploads/seed/library/project_plan.pdf"},
		{2, 6, 1, "Книга рецептов.pdf", "application/pdf", "uploads/seed/library/recipe_book.pdf"},
		{3, 7, 4, "Набор кистей.zip", "application/zip", "uploads/seed/library/brushes_pack.zip"},
		{4, 10, 2, "Лайв-микс.mp3", "audio/mpeg", "uploads/seed/library/live_mix.mp3"},
		{5, 5, 1, "Программа тренировок.pdf", "application/pdf", "uploads/seed/library/workout_plan.pdf"},
		{6, 1, 4, "Обои Алматы.zip", "application/zip", "uploads/seed/library/almaty_wallpapers.zip"},
		{7, 3, 1, "Гид путешественника.pdf", "application/pdf", "uploads/seed/library/travel_guide.pdf"},
		{8, 4, 1, "Советы по фотографии.pdf", "application/pdf", "uploads/seed/library/photography_tips.pdf"},
		{9, 10, 1, "Основы теории музыки.pdf", "application/pdf", "uploads/seed/library/music_theory.pdf"},
		{10, 4, 4, "Фото-гид по Алматы.zip", "application/zip", "uploads/seed/library/photo_guide.zip"},
		{11, 6, 5, "Гид по ресторанам.zip", "application/zip", "uploads/seed/library/restaurant_guide.zip"},
		{12, 10, 2, "Чилл-микс.mp3", "audio/mpeg", "uploads/seed/library/chill_mix.mp3"},
	}
	for _, f := range files {
		stat, err := os.Stat(f.path)
		if err != nil {
			return fmt.Errorf("seed file missing on disk: %s — run scripts/seed_assets/download.ps1 first: %w", f.path, err)
		}
		_, err = tx.Exec(ctx, `
			INSERT INTO files (id, user_id, filename, file_url, mime_type, file_size, category_id, description)
			VALUES ($1,$2,$3,$4,$5,$6,$7,'')
			ON CONFLICT (id) DO UPDATE SET
				filename = EXCLUDED.filename,
				file_url = EXCLUDED.file_url,
				mime_type = EXCLUDED.mime_type,
				file_size = EXCLUDED.file_size,
				category_id = EXCLUDED.category_id`,
			uid(pFile, f.idx), uid(pUser, f.owner), f.name,
			"/"+f.path,
			f.mime, stat.Size(), uid(pFileCat, f.category))
		if err != nil {
			return err
		}
	}
	return nil
}

// ---------- Сборы ----------

func seedSbory(ctx context.Context, tx pgx.Tx) error {
	type seedSbor struct {
		idx         int
		hostIdx     int    // 1-based index into mainUsers
		sborType    string // offline | online
		category    string
		title       string
		place       string
		description string
		scheduledAt string // RFC3339 or "" for flexible/live
		flexible    bool
		maxSlots    *int
		isLive      bool
	}
	slots := func(n int) *int { return &n }

	sbory := []seedSbor{
		{
			idx: 1, hostIdx: 2, sborType: "offline", category: "basketball",
			title:       "Баскетбол в парке — 5×5",
			place:       "Парк имени 28 гвардейцев-панфиловцев, Алматы",
			description: "Дружеский матч 5 на 5. Берите кроссы и хорошее настроение. Мяч есть.",
			scheduledAt: "2026-05-31T10:00:00+06:00",
			maxSlots:    slots(10),
		},
		{
			idx: 2, hostIdx: 3, sborType: "offline", category: "hike",
			title:       "Поход на Большое Алматинское озеро",
			place:       "БАО, Алматы",
			description: "Стартуем в 7 утра от нижней остановки. Маршрут средний, ~12 км. Берите термос и перекус.",
			scheduledAt: "2026-06-07T07:00:00+06:00",
			maxSlots:    slots(12),
		},
		{
			idx: 3, hostIdx: 2, sborType: "online", category: "other",
			title:       "Совместное кодирование — пишем open-source",
			place:       "",
			description: "Онлайн-сессия для разработчиков. Обсуждаем архитектуру, пишем тесты, делаем PR. Стек: Go + Flutter.",
			scheduledAt: "2026-05-28T19:00:00+06:00",
			maxSlots:    slots(8),
		},
		{
			idx: 4, hostIdx: 7, sborType: "offline", category: "board",
			title:       "Настольные игры у Зарины",
			place:       "ул. Достык 89, Алматы (квартира)",
			description: "Играем в Catan, Dixit и что-нибудь ещё по настроению. Еда и чай с меня, десерт с вас.",
			scheduledAt: "2026-05-30T18:00:00+06:00",
			maxSlots:    slots(6),
		},
		{
			idx: 5, hostIdx: 9, sborType: "offline", category: "cinema",
			title:       "Кино: «Дюна: Часть три» — IMAX",
			place:       "Кинотеатр MEGA Alma-Ata, IMAX зал",
			description: "Идём смотреть Дюну 3 в IMAX. Билеты покупает каждый сам, но бронируем ряд вместе.",
			scheduledAt: "2026-06-01T15:30:00+06:00",
			maxSlots:    slots(8),
		},
		{
			idx: 6, hostIdx: 5, sborType: "offline", category: "basketball",
			title:       "Утренняя пробежка по Медеу",
			place:       "Медеу, Алматы",
			description: "Бегаем каждое воскресенье! 5-8 км по трассе вокруг катка. Темп умеренный, ждём всех.",
			flexible:    true,
			scheduledAt: "2026-06-01T08:00:00+06:00",
			maxSlots:    nil,
		},
		{
			idx: 7, hostIdx: 7, sborType: "online", category: "draw",
			title:       "Скетч-сессия: рисуем вместе",
			place:       "",
			description: "Онлайн рисовалка — каждый рисует своё, но вместе веселей. Любой уровень, любой инструмент.",
			scheduledAt: "2026-05-29T20:00:00+06:00",
			maxSlots:    slots(20),
		},
		{
			idx: 8, hostIdx: 10, sborType: "online", category: "games",
			title:       "FIFA турнир — PS5",
			place:       "",
			description: "Онлайн-турнир по FIFA 26. Группа из 8 человек, плей-офф, чемпион получает вечную славу.",
			isLive:      true,
			scheduledAt: "",
			maxSlots:    slots(8),
		},
	}

	for _, s := range sbory {
		hostID := uid(pUser, s.hostIdx)
		sborID := uid(pSbor, s.idx)

		var scheduledAt *string
		if s.scheduledAt != "" {
			scheduledAt = &s.scheduledAt
		}

		_, err := tx.Exec(ctx, `
			INSERT INTO sbory (id, host_id, type, category, title, place, description,
				scheduled_at, flexible_time, max_slots, is_live)
			VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
			ON CONFLICT (id) DO UPDATE SET
				category     = EXCLUDED.category,
				title        = EXCLUDED.title,
				place        = EXCLUDED.place,
				description  = EXCLUDED.description,
				scheduled_at = EXCLUDED.scheduled_at,
				flexible_time= EXCLUDED.flexible_time,
				max_slots    = EXCLUDED.max_slots,
				is_live      = EXCLUDED.is_live`,
			sborID, hostID, s.sborType, s.category, s.title,
			s.place, s.description, scheduledAt, s.flexible, s.maxSlots, s.isLive)
		if err != nil {
			return fmt.Errorf("upsert sbor %d: %w", s.idx, err)
		}

		// Host is always an organizer member.
		_, err = tx.Exec(ctx, `
			INSERT INTO sbor_members (sbor_id, user_id, role)
			VALUES ($1,$2,'organizer')
			ON CONFLICT DO NOTHING`,
			sborID, hostID)
		if err != nil {
			return fmt.Errorf("sbor_members host %d: %w", s.idx, err)
		}
	}

	// Add participants — spread across main users, skipping the host.
	participants := []struct{ sborIdx, userIdx int }{
		{1, 1}, {1, 4}, {1, 5}, {1, 8},
		{2, 1}, {2, 4}, {2, 6}, {2, 9},
		{3, 1}, {3, 9},
		{4, 1}, {4, 2}, {4, 5},
		{5, 1}, {5, 2}, {5, 4},
		{6, 1}, {6, 3}, {6, 8}, {6, 10},
		{7, 1}, {7, 2}, {7, 3}, {7, 4},
		{8, 1}, {8, 2}, {8, 3}, {8, 4},
	}
	for _, p := range participants {
		_, err := tx.Exec(ctx, `
			INSERT INTO sbor_members (sbor_id, user_id, role)
			VALUES ($1,$2,'participant')
			ON CONFLICT DO NOTHING`,
			uid(pSbor, p.sborIdx), uid(pUser, p.userIdx))
		if err != nil {
			return fmt.Errorf("sbor_members participant sbor=%d user=%d: %w", p.sborIdx, p.userIdx, err)
		}
	}
	return nil
}

// ---------- Counters ----------

func recountCounters(ctx context.Context, tx pgx.Tx) error {
	queries := []string{
		`UPDATE users SET
			posts_count = (SELECT COUNT(*) FROM posts WHERE user_id = users.id),
			followers_count = (SELECT COUNT(*) FROM follows WHERE following_id = users.id),
			following_count = (SELECT COUNT(*) FROM follows WHERE follower_id = users.id)`,
		`UPDATE posts SET
			likes_count = (SELECT COUNT(*) FROM likes WHERE entity_id = posts.id AND entity_type = 'post'),
			comments_count = (SELECT COUNT(*) FROM comments WHERE post_id = posts.id),
			saves_count = (SELECT COUNT(*) FROM saved_posts WHERE post_id = posts.id)`,
		`UPDATE videos SET
			likes_count = (SELECT COUNT(*) FROM video_likes WHERE video_id = videos.id),
			views_count = (SELECT COUNT(*) FROM video_views WHERE video_id = videos.id)`,
	}
	for _, q := range queries {
		if _, err := tx.Exec(ctx, q); err != nil {
			return fmt.Errorf("recount: %w; query=%s", err, strings.SplitN(q, "\n", 2)[0])
		}
	}
	return nil
}
